MODULE F2PY_CONSTANTS
    IMPLICIT NONE

    INTEGER, PARAMETER :: N_PHYSICS_PARAMS=8 !Generated by user
    INTEGER, PARAMETER :: nspec=335, nReac=3213 !Generated by makerates
CONTAINS
    SUBROUTINE DUMMY_ONE()
        integer :: dummy_one_output = 1
        dummy_one_output = 2
    END SUBROUTINE DUMMY_ONE
END MODULE F2PY_CONSTANTS