MODULE F2PY_CONSTANTS
    IMPLICIT NONE

    INTEGER, PARAMETER :: N_PHYSICS_PARAMS=8 !Generated by user
    INTEGER, PARAMETER :: nspec=335, nReac=3213 !Generated by makerates
CONTAINS
    SUBROUTINE DUMMY_ONE(dummy_one_output)
        integer, intent(out) :: dummy_one_output
        dummy_one_output = 1
    END SUBROUTINE DUMMY_ONE
END MODULE F2PY_CONSTANTS