MODULE F2PY_CONSTANTS
    INTEGER, PARAMETER :: N_PHYSICS_PARAMS=8 !Generated by user
    INTEGER, PARAMETER :: nspec=335, nReac=3169 !Generated by makerates
    INTEGER, PARAMETER :: NCOOLANTS=7 !Generated by makerates
    INTEGER, PARAMETER :: n_dvode_stats=18 !Generated by makerates
    
    ! Coolant file names and species names
    CHARACTER(LEN=15), PARAMETER :: coolantFiles(NCOOLANTS)=(/"ly-a.dat       ","12c+_nometa.dat","16o.dat        ","12c.dat        ","12co.dat       ","p-h2.dat       ","o-h2.dat       "/)
    CHARACTER(LEN=4), PARAMETER :: coolantNames(NCOOLANTS)=(/"H   ","C+  ","O   ","C   ","CO  ","p-H2","o-H2"/)
END MODULE F2PY_CONSTANTS