import subprocess
import sys
from pathlib import Path

import pytest

from uclchem.makerates.makerates import run_makerates

UCLCHEM_ROOT_DIR = Path(__file__).parent.parent
MAKERATES_DIR = UCLCHEM_ROOT_DIR / "Makerates"
PYTHON_ROOT_DIR = UCLCHEM_ROOT_DIR / "src" / "uclchem"
FORTRAN_ROOT_DIR = UCLCHEM_ROOT_DIR / "src" / "fortran_src"


MAKERATES_WRITTEN_FILES = [
    PYTHON_ROOT_DIR / "species.csv",
    PYTHON_ROOT_DIR / "reactions.csv",
    FORTRAN_ROOT_DIR / "network.f90",
    FORTRAN_ROOT_DIR / "f2py_constants.f90",
    FORTRAN_ROOT_DIR / "odes.f90",
]


def test_makerates_generates_same_files(tmp_path: Path):
    """Test that MakeRates with default settings makes no changes to the network.

    Test that running MakeRates with the default user settings creates the same network
    as what is currently in the repository. This is for consistency.
    If a different network ships than what would be
    generated by the default settings, that is hard to find out as a user.

    """
    run_makerates(
        MAKERATES_DIR / "user_settings.yaml", output_directory=tmp_path, write_files=True
    )

    tmp_files = [tmp_path / file.name for file in MAKERATES_WRITTEN_FILES]
    for file, tmp_file in zip(MAKERATES_WRITTEN_FILES, tmp_files, strict=True):
        assert file.read_text() == tmp_file.read_text()


def test_makerates_invalid_log_level_raises():
    result = subprocess.run(
        [
            sys.executable,
            "MakeRates.py",
            "--verbosity-file",
            "INVALID_LOG_LEVEL",
        ],
        capture_output=True,
        text=True,
        cwd=MAKERATES_DIR,
    )

    assert "invalid choice" in result.stderr


VERBOSITIES = ("DEBUG", "INFO", "WARNING")


def _verify_only_allowed_log_levels(
    lines: list[str], level: str, output_path: str | Path
) -> bool:
    verbosity_index = VERBOSITIES.index(level)
    verbosity_good = False
    output_path = str(output_path)
    for line in lines:
        if level in line:
            verbosity_good = True
        if "Configured logging: " in line:
            # Gives both logging levels in this line,
            # so possibly also prints the level lower than what is allowed for this
            # logger if the other logger is lower.
            continue
        if output_path in line:
            # Contains 'tmp_path', which, because we parametrize the test,
            # will contain the log level of the logger to the file,
            # which might cause the stdout logger to fail, so we ignore this line.
            continue
        not_allowed_level_found = any(
            verb in line for verb in VERBOSITIES[:verbosity_index]
        )
        if not_allowed_level_found:
            return False
    return verbosity_good


# We need to run the different file verbosities sequentially, otherwise the different
# levels start logging into the same file, which would cause the tests to fail.
# See for example https://github.com/uclchem/UCLCHEM/actions/runs/32345174023/job/96352894544?pr=195
@pytest.mark.parametrize("verbosity_file", VERBOSITIES)
def test_makerates_verbosity(tmp_path: Path, verbosity_file):
    logfile = MAKERATES_DIR / "makerates.log"

    for verbosity_stdout in VERBOSITIES:
        result = subprocess.run(
            [
                sys.executable,
                "MakeRates.py",
                "--verbosity-stdout",
                verbosity_stdout,
                "--verbosity-file",
                verbosity_file,
                "--output-directory",
                tmp_path,
            ],
            check=True,
            capture_output=True,
            text=True,
            cwd=MAKERATES_DIR,
        )

        for file in MAKERATES_WRITTEN_FILES:
            output_file = tmp_path / file.name
            assert output_file.is_file()
            output_file.unlink()

        assert _verify_only_allowed_log_levels(
            logfile.read_text().split("\n"), verbosity_file, tmp_path
        )
        assert _verify_only_allowed_log_levels(
            result.stdout.split("\n"),
            verbosity_stdout,
            tmp_path,
        )


def test_makerates_dry_run_doesnt_write(tmp_path: Path):
    tmp_filepaths = [tmp_path / file.name for file in MAKERATES_WRITTEN_FILES]

    _result = subprocess.run(
        [sys.executable, "MakeRates.py", "--dry-run", "--output-directory", tmp_path],
        check=True,
        capture_output=True,
        text=True,
        cwd=MAKERATES_DIR,
    )

    for filepath in tmp_filepaths:
        assert not filepath.exists()
