MODULE F2PY_CONSTANTS
    USE CONSTANTS, only: dp
    INTEGER, PARAMETER :: N_PHYSICS_PARAMS={n_physical_parameters} !Generated by user
    INTEGER, PARAMETER :: nspec={n_species}, nReac={n_reactions} !Generated by makerates
    INTEGER, PARAMETER :: NCOOLANTS={n_coolants} !Generated by makerates
    INTEGER, PARAMETER :: MAX_COOLANTS={max_coolants} !Generated by makerates
    INTEGER, PARAMETER :: N_DVODE_STATS={n_dvode_stats} !DVODE solver statistics per timestep
    INTEGER, PARAMETER :: N_TOTAL_LEVELS={n_total_levels} !Total energy levels across all coolants
    INTEGER, PARAMETER :: N_SE_STATS_PER_COOLANT={n_se_stats_per_coolant} !SE solver stats per coolant

    ! Coolant file names and species names
    CHARACTER(LEN={coolant_file_len}), PARAMETER :: coolantFiles(NCOOLANTS)=({coolant_files})
    CHARACTER(LEN={coolant_name_len}), PARAMETER :: coolantNames(NCOOLANTS)=({coolant_names})

    ! Parent species names for coolant-to-network abundance mapping
    CHARACTER(LEN={parent_name_len}), PARAMETER :: coolantParentNames(NCOOLANTS)=({parent_names})

    ! Conversion factors and modes are appended by write_f90_constants via array_to_string

    ! Default directory for collisional rate files (can be changed at runtime via HeatingSettings)
    CHARACTER(256) :: coolantDataDir = "{coolant_data_dir}"
END MODULE F2PY_CONSTANTS
