MODULE F2PY_CONSTANTS
    INTEGER, PARAMETER :: N_PHYSICS_PARAMS={n_physical_parameters} !Generated by user
    INTEGER, PARAMETER :: nspec={n_species}, nReac={n_reactions} !Generated by makerates
    INTEGER, PARAMETER :: NCOOLANTS={n_coolants} !Generated by makerates

    ! Coolant file names and species names
    CHARACTER(LEN={coolant_file_len}), PARAMETER :: coolantFiles(NCOOLANTS)=({coolant_files})
    CHARACTER(LEN={coolant_name_len}), PARAMETER :: coolantNames(NCOOLANTS)=({coolant_names})

    ! Default directory for collisional rate files (can be changed at runtime via HeatingSettings)
    CHARACTER(256) :: coolantDataDir = "{coolant_data_dir}"
END MODULE F2PY_CONSTANTS