module F2PY_CONSTANTS
    use CONSTANTS, only: dp

    implicit none

    public

    integer, parameter :: N_PHYSICS_PARAMS={n_physical_parameters}  !Generated by user
    integer, parameter :: nspec={n_species}, nReac={n_reactions}  !Generated by makerates
    integer, parameter :: NCOOLANTS={n_coolants}  !Generated by makerates
    integer, parameter :: MAX_COOLANTS={max_coolants}  !Generated by makerates
    integer, parameter :: N_DVODE_STATS={n_dvode_stats}  !DVODE solver statistics per timestep
    integer, parameter :: N_TOTAL_LEVELS={n_total_levels}  !Total energy levels across all coolants
    integer, parameter :: N_SE_STATS_PER_COOLANT={n_se_stats_per_coolant}  !SE solver stats per coolant

    integer, parameter :: MISSING_VALUE_INTEGER={missing_value_integer}  !Integer to indicate missing value
    real(dp), parameter :: MISSING_VALUE_FLOAT={missing_value_float}_dp  !Float to indicate missing value
    integer, parameter :: NO_REACTANT_OR_PRODUCT={no_reactant_or_product}  !Indicates that the reaction does not have this many reactants or products

    ! Coolant file names and species names
    character(LEN={coolant_file_len}), parameter :: coolantFiles(NCOOLANTS)=({coolant_files})
    character(LEN={coolant_name_len}), parameter :: coolantNames(NCOOLANTS)=({coolant_names})

    ! Parent species names for coolant-to-network abundance mapping
    character(LEN={parent_name_len}), parameter :: coolantParentNames(NCOOLANTS)=({parent_names})

    ! Conversion factors and modes are appended by write_f90_constants via array_to_string

    ! Per-coolant on/off toggle (can be changed at runtime via HeatingSettings)
    ! Generated by makerates with all coolants enabled by default

    ! Default directory for collisional rate files (can be changed at runtime via HeatingSettings)
    character(256) :: coolantDataDir = "{coolant_data_dir}"
end module F2PY_CONSTANTS
