# This file was machine generated with Makerates on 2025-11-10 21:38:53.472431
# This file contains the default magic numbers that ensure that fortran and
# python are in sync. If you adjust anything here, you must:
# 1. rerun makerates (this puts the magic numbers in fortran)
# 2. reinstall the python (this compiles fortran and the python wrapper)
# 3. rerun the tests (this ensures that everything is working)

# The physical parameters in the model, this is used in the fortran bits to
# ensure the physical parameter array is created in the right size.
PHYSICAL_PARAMETERS = [
    "Time",
    "Density",
    "gasTemp",
    "dustTemp",
    "Av",
    "radfield",
    "zeta",
    "dstep",
]
# The number of timepoints we use for interfacing with the fortran code,
# increase this for long/expensive models.
TIMEPOINTS = 500
# The number of physical parameters, species and reactions, this is automatically generated by makerates
N_PHYSICAL_PARAMETERS = 8
n_species = 335
n_reactions = 3203
n_heating_terms = 19
