# This file was machine generated with Makerates on 2026-02-04 23:37:26.669789
# This file contains the default magic numbers that ensure that fortran and
# python are in sync. If you adjust anything here, you must:
# 1. rerun makerates (this puts the magic numbers in fortran)
# 2. reinstall the python (this compiles fortran and the python wrapper)
# 3. rerun the tests (this ensures that everything is working)

# The physical parameters in the model, this is used in the fortran bits to
# ensure the physical parameter array is created in the right size.
PHYSICAL_PARAMETERS = [
    "Time",
    "Density",
    "gasTemp",
    "dustTemp",
    "Av",
    "radfield",
    "zeta",
    "dstep",
]
# The number of timepoints we use for interfacing with the fortran code,
# increase this for long/expensive models.
TIMEPOINTS = 2000
# The number of physical parameters, species and reactions, this is automatically generated by makerates
N_PHYSICAL_PARAMETERS = 8
n_species = 335
n_reactions = 3205
N_DVODE_STATS = 18
DVODE_STAT_NAMES = [
    "ISTATE",
    "HU",
    "HCUR",
    "TCUR",
    "TOLSF",
    "NST",
    "NFE",
    "NJE",
    "NQU",
    "NQCUR",
    "IMXER",
    "LENRW",
    "LENIW",
    "NLU",
    "NNI",
    "NCFN",
    "NETF",
    "CPU_TIME",
]
default_param_dictionary = {
    "initialtemp": 10.0,
    "initialdens": 100.0,
    "finaldens": 100000.0,
    "currenttime": 0.0,
    "finaltime": 5000000.0,
    "radfield": 1.0,
    "zeta": 1.0,
    "rout": 0.05,
    "rin": 0.0,
    "baseav": 2.0,
    "points": 1,
    "bm0": 1.0,
    "freezefactor": 1.0,
    "endatfinaldensity": False,
    "freefall": True,
    "freefallfactor": 1.0,
    "desorb": True,
    "h2desorb": True,
    "crdesorb": True,
    "uvdesorb": True,
    "thermdesorb": True,
    "instantsublimation": True,
    "cosmicrayattenuation": True,
    "ionmodel": "L",
    "improvedh2crpdissociation": True,
    "outputfile": None,
    "columnfile": None,
    "ratefile": None,
    "fluxfile": None,
    "writestep": 1,
    "abundsavefile": None,
    "abundloadfile": None,
    "metallicity": 1.0,
    "ion": 2,
    "fh": 0.5,
    "fhe": 0.1,
    "fc": 0.000177,
    "fo": 0.000334,
    "fn": 6.18e-05,
    "fs": 3.51e-06,
    "fmg": 2.256e-06,
    "fsi": 1.78e-06,
    "fcl": 3.39e-08,
    "fp": 7.78e-08,
    "ffe": 2.01e-07,
    "ff": 3.6e-08,
    "fd": 0.0,
    "fli": 0.0,
    "fna": 0.0,
    "fpah": 0.0,
    "f15n": 0.0,
    "f13c": 0.0,
    "f18o": 0.0,
    "reltol": 1e-08,
    "abstol_factor": 1e-14,
    "abstol_min": 1e-25,
    "mxstep": 10000,
    "ebmaxh2": 1210.0,
    "ebmaxcr": 1210.0,
    "ebmaxuvcr": 10000.0,
    "epsilon": 0.01,
    "uv_yield": 0.03,
    "phi": 100000.0,
    "uvcreff": 0.001,
    "omega": 0.5,
}
